name: JimRCameron
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12021097913384438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b2429'
    - '#030b0e'
    - '#877f7c'
    - '#695f5d'
    - '#c1b5b5'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.8816362938378006
purpose: []
