name: JimRCameron
favicon: null
layout_spectrum: 0.50271
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1B2429'
    - '#030B0E'
    - '#877F7C'
    - '#695F5D'
    - '#C1B5B5'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
