analytics: {}
color:
  brandColors:
    - '#1b2429'
    - '#030b0e'
    - '#877f7c'
    - '#695f5d'
    - '#c1b5b5'
  brandStrength: 1
  lightness: 0.5625
  rhythmicContrast: 0.8816362938378006
  saturation: 0.0625
cta: {}
layout_spectrum: 1
name: JimRCameron
opengraph: {}
purpose: []
typography_spectrum: 1
