name: JimRCameron
favicon: null
layout_spectrum: 0.06195327057503164
typography_spectrum: 0.12021097913384438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5915909139439464
  lightness: 0.034279740415513515
  saturation: 0.40332832909189165
  rhythmicContrast: 0.8816362938378006
purpose: []
