name: JimRCameron
favicon: null
layout_spectrum: 0.06195327057503164
typography_spectrum: 0.12021097913384438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0b0a'
    - '#ac3838'
    - '#8b6149'
    - '#949283'
    - '#f35953'
  brandStrength: 0.6875
  lightness: 0.034279740415513515
  saturation: 0.40332832909189165
  rhythmicContrast: 0.8816362938378006
purpose: []
